var Game = require("./game");
var Room = require("./room");
var Table = require("./table");
var Player = require("./player");

var room = new Room("Test Room");
var table = new Table(1);
table.setName("Test Room");
room.tables = table;
var game = new Game();
table.gameObj = game;
table.pack = game.pack;
table.cardOnTable = table.gameObj.playFirstCardToTable(table.pack);
var player = new Player("I'm-a-unique-ID");
player.setName("Tamas");
room.addPlayer(player);
table.addPlayer(player);
player.hand = table.gameObj.drawCard(table.pack, 5, "", 1);
console.log(room);
console.log(table.players);